tuple1=(1,4,9,10,-1)
tuple2=('Jahangir', "Neela")
tuple3=("Jahangir", 1, "Wasee", 5)
tuple4=(10,)
tuple5=(10)
tuple6=('Jahangir',)
tuple7=('Jahangir')
list1=['Jahangir', 'Wasee', 'Neela', "zahraa"]
tuple8=tuple(list1)
print(f'tuple1 - {type(tuple1)}')
print(f'tuple2 - {type(tuple2)}')
print(f'tuple3 - {type(tuple3)}')
print(f'tuple4 - {type(tuple4)}')
print(f'tuple5 - {type(tuple5)}')
print(f'tuple6 - {type(tuple6)}')
print(f'tuple7 - {type(tuple7)}')

print(tuple1[3])
print(tuple2[1])
print(tuple3[-2])

print(tuple1.count(10))
print(list1)
print(tuple8)
print(tuple8+tuple1)